@token=

### getBand
GET http://localhost:3003/band?name=pink

### Register Band
POST http://localhost:3003/band/register
Content-Type: application/json
Authorization: {{token}}

{
   "name":"The Score",
   "musicGenre": "Rock Alternativo",
   "responsible": "Eddie Anthony"
}

###
DELETE http://localhost:3003/